# Generated by Django 5.2.4 on 2025-07-04 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('color', models.CharField(help_text='Tailwind CSS rang kodi (masalan, #AFFF6C)', max_length=7, verbose_name='Rang')),
                ('icon', models.CharField(blank=True, help_text="Heroicons uchun belgi nomi (masalan, 'hi-bolt')", max_length=50, null=True, verbose_name='Belgi')),
            ],
            options={
                'verbose_name': 'Maqsad kategoriyasi',
                'verbose_name_plural': 'Maqsad kategoriyalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='users.goalcategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Maqsad',
                'verbose_name_plural': 'Maqsadlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
